apiVersion: v1
kind: Pod
metadata:
  name: example-pod

spec:
  containers:
  - name: echo-server
    image: localhost:32000/my-image
    ports:
    - containerPort: 8080
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 1
